version: "3.7"
services:
  app:
    build:
      args:
        user: alisson
        uid: 1000
      context: ./laravel-app/
      dockerfile: Dockerfile
    image: boltons
    container_name: boltons-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./laravel-app/:/var/www
      - ./.env:/var/www/.env
    networks:
      - arquivei-private

  db:
    image: mysql:8
    container_name: boltons-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - arquivei-private

  nginx:
    image: nginx:alpine
    container_name: boltons-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel-app:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - arquivei-private

networks:
  arquivei-private:
    driver: bridge
